apiVersion: v1
kind: Secret
metadata: 
  name: mariadb-secrets
  namespace: prometheus
type: Opaque
data: 
  MYSQL_DATABASE:  aG9tZS1uYw==  ## home-ns
  MYSQL_USER: YmVydHJhbmQ=  ## bertrand 
  MYSQL_PASSWORD: ZmVybnNlaGVyMTI=  ## fernseher12
  MYSQL_ROOT_PASSWORD: ZmVybnNlaGVyMTI=  ## fernseher12
  
